config/routes.rb
Rails.application.routes.draw do
  resources :footertexts
  resources :navtexts
  resources :logotexts
  resources :templates
  resources :sections, except: [:show, :new, :index]
  resources :categories
  resources :blogs
  resources :body_colors
  resources :text_colors
  resources :designs, except: [:show, :index]
  devise_for :cmsadmins     
  resources :homes
  get 'errors/not_found'
  match "/404", :to => "errors#not_found", :via => :all 
  match "/500", :to => "errors#internal_server_error", :via => :all      
    
  get "/pages" => "pages#index"    
  get '/:id' => 'pages#show', as: :page
  patch '/:id' => 'pages#update'    
  put '/:id' => 'pages#update'    
  delete '/:id' => 'pages#destroy'    
  resources :pages, except: [:show, :delete, :update]	

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'homes#index', as: :root        
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :category
    extend FriendlyId
    friendly_id :title, use: :slugged 
  if Rails.env.production?    
      has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/:style/missing2.png", :storage => :cloudinary, :path => ':id/:style/:filename'
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/  
  else
      has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/:style/missing2.png"
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  end         
end

app/models/body_color.rb
class BodyColor < ApplicationRecord
    has_many :designs, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :blogs, dependent: :destroy
    extend FriendlyId
    friendly_id :title, use: :slugged    
end

app/models/cmsadmin.rb
class Cmsadmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/design.rb
class Design < ApplicationRecord
    belongs_to :text_color
    belongs_to :body_color
end

app/models/footertext.rb
class Footertext < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
  # attribute :text_size, :integer, default: 22   
  if Rails.env.production?    
      has_attached_file :image, styles: { medium: "450x300>", thumb: "200x150>" }, default_url: "/assets/:style/missing.png", :storage => :cloudinary, :path => ':id/:style/:filename'
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/  
  else
      has_attached_file :image, styles: { medium: "450x300>", thumb: "200x150>" }, default_url: "/assets/:style/missing.png"
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/  
  end    
    
   
   

end

app/models/logotext.rb
class Logotext < ApplicationRecord
end

app/models/navtext.rb
class Navtext < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged 
end

app/models/section.rb
class Section < ApplicationRecord
    before_save do
      self.option.gsub!(/[\[\]\"]/, "") if attribute_present?("option")
    end    
end

app/models/template.rb
class Template < ApplicationRecord
end

app/models/text_color.rb
class TextColor < ApplicationRecord
    has_many :designs, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_cmsadmin!, except: [:index, :show]    

  def index
    @blogs = Blog.order(" created_at DESC").all
  end

  def show
  end

  def new
    @blog = Blog.new
    @category = Category.all
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :body, :category_id, :image)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/logotexts_helper.rb
module LogotextsHelper
end

app/helpers/navtexts_helper.rb
module NavtextsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
def checked(area)
  @section.option.nil? ? false : @section.option.match(area)
end
    
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul><br>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>      

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title, class: "form-control" %><br>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body, class: "form-control", rows: 10 %><br>
  </div>

      <div class="field">
      <%= form.label :category %>: </br>
        <%= form.collection_select :category_id, Category.all, :id , :title, :include_blank => "select One" %>
        &nbsp; &nbsp;<%= link_to 'Add New Category', new_category_path %>
      </div><br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="container">
<h1>Editing Blog</h1>
<%= render 'form', blog: @blog %>
</div>

app/views/blogs/index.html.erb
<div class="jumbotron text-center">
  <h1>Blogs</h1>
</div>

<br>
<div class="
    <% @templates.each do |template| %>
        <% if template.bar == 5 %>container-fluid<% else %>container<% end %>
    <% end%>">
    <% @blogs.each do |blog| %>
        <div class="docr col-sm-4 col-xs-12">
          <div class="panel panel-default text-center">
            <div class="panel-body" style="word-wrap:break-word;">
                <%= image_tag blog.image.url(:medium) %>  
            <p><small><% if blog.created_at > Time.now.beginning_of_day %>
					<%="#{time_ago_in_words(blog.created_at)} ago"%><% else %>
					<%= blog.created_at.strftime("%b %d, %Y") %><% end %> by Admin  | Category: <%= link_to blog.category.title, category_path(:id => blog.category.id) %></small></p>
            <hr>    
            <h2><%= link_to blog.title.truncate(55), blog %></h2>
            <p><%= truncate(strip_tags(blog.body), length: 300) %></p>

            </div>
          </div>      
        </div>
    <% end %>
</div>

<script>
	$(function() {
		$('.docr').matchHeight({
		byRow: true,
		property: 'height',
		target: null,
		remove: false
	});
	});
</script>

app/views/blogs/new.html.erb
<div class="container">
<h1>New Blog  <small>&nbsp; &nbsp; *<small>Add Category before creating Blog &nbsp; &nbsp;<%= link_to 'Add New Category', new_category_path, class: "btn btn-default btn-sm" %></small></small></h1>

<%= render 'form', blog: @blog %>

</div>

app/views/blogs/show.html.erb
<div class="jumbotron text-center">
  <h1><%= @blog.title %></h1>
  <p>
      <small>
          <% if @blog.created_at > Time.now.beginning_of_day %><%="#{time_ago_in_words(@blog.created_at)} ago"%>
          <% else %><%= @blog.created_at.strftime("%b %d, %Y") %><% end %> by <em style="color: red;">Admin</em> in
           <%= link_to @blog.category.title, category_path(:id => @blog.category.id) %>
      </small>
  </p>
  <% if cmsadmin_signed_in? %>
    <div class="panel-footer">
        <td><%= link_to 'Edit', edit_blog_path(@blog), class: "btn btn-info btn-sm" %></td>
        <td><%= link_to 'Destroy', @blog, method: :delete, class: "btn btn-warning btn-sm", data: { confirm: 'Are you sure?' } %></td>
    </div>    
  <% end %>
</div>

<div style="word-wrap:break-word;" class="
    <% @templates.each do |template| %>
        <% if template.bar == 5 %>container-fluid<% else %>container<% end %>
    <% end%>">
<div class="text-center">  
    <%= image_tag @blog.image.url(:medium) %>  
</div> 
    
<p><%= simple_format @blog.body %></p>

<br><br><br>
</div>