config/routes.rb
Rails.application.routes.draw do
  resources :footertexts
  resources :navtexts
  resources :logotexts
  resources :templates
  resources :sections, except: [:show, :new, :index]
  resources :categories
  resources :blogs
  resources :body_colors
  resources :text_colors
  resources :designs, except: [:show, :index]
  devise_for :cmsadmins     
  resources :homes
  get 'errors/not_found'
  match "/404", :to => "errors#not_found", :via => :all 
  match "/500", :to => "errors#internal_server_error", :via => :all      
    
  get "/pages" => "pages#index"    
  get '/:id' => 'pages#show', as: :page
  patch '/:id' => 'pages#update'    
  put '/:id' => 'pages#update'    
  delete '/:id' => 'pages#destroy'    
  resources :pages, except: [:show, :delete, :update]	

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'homes#index', as: :root        
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :category
    extend FriendlyId
    friendly_id :title, use: :slugged 
  if Rails.env.production?    
      has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/:style/missing2.png", :storage => :cloudinary, :path => ':id/:style/:filename'
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/  
  else
      has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/:style/missing2.png"
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  end         
end

app/models/body_color.rb
class BodyColor < ApplicationRecord
    has_many :designs, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :blogs, dependent: :destroy
    extend FriendlyId
    friendly_id :title, use: :slugged    
end

app/models/cmsadmin.rb
class Cmsadmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/design.rb
class Design < ApplicationRecord
    belongs_to :text_color
    belongs_to :body_color
end

app/models/footertext.rb
class Footertext < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
  # attribute :text_size, :integer, default: 22   
  if Rails.env.production?    
      has_attached_file :image, styles: { medium: "450x300>", thumb: "200x150>" }, default_url: "/assets/:style/missing.png", :storage => :cloudinary, :path => ':id/:style/:filename'
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/  
  else
      has_attached_file :image, styles: { medium: "450x300>", thumb: "200x150>" }, default_url: "/assets/:style/missing.png"
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/  
  end    
    
   
   

end

app/models/logotext.rb
class Logotext < ApplicationRecord
end

app/models/navtext.rb
class Navtext < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged 
end

app/models/section.rb
class Section < ApplicationRecord
    before_save do
      self.option.gsub!(/[\[\]\"]/, "") if attribute_present?("option")
    end    
end

app/models/template.rb
class Template < ApplicationRecord
end

app/models/text_color.rb
class TextColor < ApplicationRecord
    has_many :designs, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def show
      @blogs = @category.blogs  
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to new_blog_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:title)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/logotexts_helper.rb
module LogotextsHelper
end

app/helpers/navtexts_helper.rb
module NavtextsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
def checked(area)
  @section.option.nil? ? false : @section.option.match(area)
end
    
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :category_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h3>
  <strong>Category:</strong>
  <%= @category.title %>
</h3>

<div class="
    <% @templates.each do |template| %>
        <% if template.bar == 5 %>container-fluid<% else %>container<% end %>
    <% end%>">
    <% @blogs.each do |blog| %>
        <div class="docr col-sm-4 col-xs-12">
          <div class="panel panel-default text-center">
            <div class="panel-body" style="word-wrap:break-word;">
                <%= image_tag blog.image.url(:medium) %>  
            <p><small><% if blog.created_at > Time.now.beginning_of_day %>
					<%="#{time_ago_in_words(blog.created_at)} ago"%><% else %>
					<%= blog.created_at.strftime("%b %d, %Y") %><% end %> by Admin  | Category: <%= link_to blog.category.title, category_path(:id => blog.category.id) %></small></p>
            <hr>    
            <h2><%= link_to blog.title.truncate(55), blog %></h2>
            <p><%= truncate(strip_tags(blog.body), length: 300) %></p>

            </div>
          </div>      
        </div>
    <% end %>
</div>

<script>
	$(function() {
		$('.docr').matchHeight({
		byRow: true,
		property: 'height',
		target: null,
		remove: false
	});
	});
</script>