config/routes.rb
Rails.application.routes.draw do
  resources :footertexts
  resources :navtexts
  resources :logotexts
  resources :templates
  resources :sections, except: [:show, :new, :index]
  resources :categories
  resources :blogs
  resources :body_colors
  resources :text_colors
  resources :designs, except: [:show, :index]
  devise_for :cmsadmins     
  resources :homes
  get 'errors/not_found'
  match "/404", :to => "errors#not_found", :via => :all 
  match "/500", :to => "errors#internal_server_error", :via => :all      
    
  get "/pages" => "pages#index"    
  get '/:id' => 'pages#show', as: :page
  patch '/:id' => 'pages#update'    
  put '/:id' => 'pages#update'    
  delete '/:id' => 'pages#destroy'    
  resources :pages, except: [:show, :delete, :update]	

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'homes#index', as: :root        
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :category
    extend FriendlyId
    friendly_id :title, use: :slugged 
  if Rails.env.production?    
      has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/:style/missing2.png", :storage => :cloudinary, :path => ':id/:style/:filename'
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/  
  else
      has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/:style/missing2.png"
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  end         
end

app/models/body_color.rb
class BodyColor < ApplicationRecord
    has_many :designs, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :blogs, dependent: :destroy
    extend FriendlyId
    friendly_id :title, use: :slugged    
end

app/models/cmsadmin.rb
class Cmsadmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/design.rb
class Design < ApplicationRecord
    belongs_to :text_color
    belongs_to :body_color
end

app/models/footertext.rb
class Footertext < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
  # attribute :text_size, :integer, default: 22   
  if Rails.env.production?    
      has_attached_file :image, styles: { medium: "450x300>", thumb: "200x150>" }, default_url: "/assets/:style/missing.png", :storage => :cloudinary, :path => ':id/:style/:filename'
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/  
  else
      has_attached_file :image, styles: { medium: "450x300>", thumb: "200x150>" }, default_url: "/assets/:style/missing.png"
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/  
  end    
    
   
   

end

app/models/logotext.rb
class Logotext < ApplicationRecord
end

app/models/navtext.rb
class Navtext < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged 
end

app/models/section.rb
class Section < ApplicationRecord
    before_save do
      self.option.gsub!(/[\[\]\"]/, "") if attribute_present?("option")
    end    
end

app/models/template.rb
class Template < ApplicationRecord
end

app/models/text_color.rb
class TextColor < ApplicationRecord
    has_many :designs, dependent: :destroy
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/navtexts_helper.rb
module NavtextsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
def checked(area)
  @section.option.nil? ? false : @section.option.match(area)
end
    
end

app/views/layouts/_docimer_sidebar.html.erb
<!-------- Docimer SideBar Contents -------->
<div class="container-fluid text-center side inside">
    
<!-------- Docimer SideBar Static navbar -------->
<ul class="docile-bar" oncontextmenu="return false">
    <li><a class="active"><strong><em>Docimer Admin!</em></strong></a></li>
          <li><%= link_to "Account", edit_cmsadmin_registration_path %></li>
          <li><%= link_to "Sign out", destroy_cmsadmin_session_path, :method => :delete %></li>
</ul><br>       
    
 <!-------- Docimer SideBar Home Section --------> 
<div class="col-md-12">      
    <div class="panel panel-danger no-padding">
      <div class="panel-heading" align="center">Builder<br></div>
      <div class="panel-body">    
            <small>
                <table class="table">
                    <tbody>
                        <tr class="dash"><%= form_with(model: @template, local: true) do |f| %> 
                        <td><strong>Header  </strong></td>
                        <td><%= f.select :bar, options_for_select([["Select", ""], "1", "2", "3", "4", "5", "6"]) %></td> 
                        <td><%= f.submit "Go", method: :get %></td>    
                        </tr> <% end %>                     
                        <% if  Home.all.count == 1 %>
                        <% @homes.each do |home| %>
                        <tr class="info">
                        <td><strong>HomePage </strong></td>
                        <td><%= link_to 'Edit Home', edit_home_path(home), method: :get, class: "btn btn-primary btn-xs" %></td> 
                        <td><%= link_to 'Destroy Home', home, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>    
                        <% end %>
                        <% else %>
                        <td><strong>HomePage </strong></td>
                        <td><%= link_to 'New Home', new_home_path, method: :get, class: "btn btn-primary btn-sm" %></td>
                        <td> --- </td>                            
                        </tr>     
                        <% end %>
                        <tr class="dash">
                        <td><strong>Pages </strong></td>
                        <td><%= link_to 'New Page', new_page_path, method: :get, class: "btn btn-primary btn-xs" %></td> 
                        <td><%= link_to 'Pages', pages_path, method: :get, class: "btn btn-primary btn-xs" %></td>    
                        </tr>
                        <tr class="info">
                        <td><strong>Blogs </strong></td>
                        <td><%= link_to 'New Blog', new_blog_path, method: :get, class: "btn btn-primary btn-xs" %></td> 
                        <td><%= link_to 'Blogs', blogs_path, method: :get, class: "btn btn-primary btn-xs" %></td>    
                        </tr>                          
                    </tbody>
                </table>
            </small>
        </div> 
    </div>             
</div>
    
    
 <!-------- Docimer SideBar Design Section -------->        
  <div class="col-md-12">     
    <div class="panel panel-warning">
      <div class="panel-heading" align="center">Design<br></div>
      <div class="panel-body">
            <small>
                <table class="table">
                    <tbody> 
                    <%= form_with(model: @design, local: true) do |form| %>    
                        <tr class="default">
                        <td><%= form.collection_select :text_color_id, TextColor.all, :id , :name, :include_blank => "Text Color" %></td>    
                            
                        <td><%= form.collection_select :body_color_id, BodyColor.all, :id , :name, :include_blank => "Body Color" %></td> 
                        <td><%= form.submit "Select Design", method: :get %></td>    
                        </tr>
                    <% end %> 
                         <tr class="danger text-center"> 
                            <th class="text-center">Text Color</th>
                            <th class="text-center"> -- </th>
                            <th class="text-center">Body Color</th>
                        </tr>            
                        <% @designs.each do |design| %>
                          <tr class="default">  
                            <td><%= design.text_color.name %></td>
                            <td><em style="color: red;"><--current--></em></td>   
                            <td><%= design.body_color.name %></td>
                          </tr>     
                        <% end %> 
                           <tr class="danger">  
                            <td><%= link_to 'New Text Color', new_text_color_path, class: "btn btn-default btn-xs" %></td>
                            <td>-<small><strong>Add Colors Here</strong></small>-</td>   
                            <td><%= link_to 'New Body Color', new_body_color_path, class: "btn btn-default btn-xs" %></td>
                          </tr>                         
                    </tbody>
                </table>
            </small>                                  
        </div>
      </div>
    </div><br>
 
 <!-------- Add Remove Blogs from Navbar -------->        
<div class="col-md-12">     
    <div class="panel panel-success">
      <div class="panel-heading" align="center">Add/Remove Blogs from Navbar<br></div>
      <div class="panel-body">        
        <%= form_with(model: @section, local: true) do |form| %>
            <%= label_tag 'Add Blog to Header', 'Add Blog' %>
            <%= check_box_tag 'section[option][]', 'Add Blog', checked('Add Blog') %>
            <%= label_tag 'Remove Blog from Header', 'Remove Blog' %>
            <%= check_box_tag 'section[option][]', '', checked('') %>
            <%= form.submit "Go", method: :get %>
        <% end %>
        </div>
      </div>   
</div>  
    
<div class="col-md-12">     
    <div class="panel panel-success">
      <div class="panel-heading" align="center">Miscellaneous<br></div>
      <div class="panel-body">
            <small>
                <table class="table">
                    <tbody>                       
                        <% if  Logotext.all.count == 1 %>
                        <% @logotexts.each do |logotext| %>
                        <tr class="default">
                        <td><strong>Logo Text </strong></td>
                        <td><%= link_to 'Edit Logo', edit_logotext_path(logotext), method: :get, class: "btn btn-info btn-xs" %></td> 
                        <td><%= link_to 'Destroy Logo', logotext, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>    
                        <% end %>
                        <% else %>
                        <td><strong>Logo Text </strong></td>
                        <td><%= link_to 'New Logo', new_logotext_path, method: :get, class: "btn btn-info btn-xs" %></td>
                        <td> --- </td>                            
                        </tr>     
                        <% end %>
                        </tbody><tbody>
                        <% if  Navtext.all.count == 1 %>
                        <% @navtexts.each do |navtext| %>
                        <tr class="default">
                        <td><strong>Nav Text </strong></td>
                        <td><%= link_to 'Edit NavText', edit_navtext_path(navtext), method: :get, class: "btn btn-info btn-xs" %></td> 
                        <td><%= link_to 'Destroy NavText', navtext, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>    
                        <% end %>
                        <% else %>
                        <td><strong>Nav Text </strong></td>
                        <td><%= link_to 'New NavText', new_navtext_path, method: :get, class: "btn btn-info btn-xs" %></td>
                        <td> --- </td>                            
                        </tr>     
                        <% end %>       
                        </tbody><tbody>
                        <% if  Footertext.all.count == 1 %>
                        <% @footertexts.each do |footertext| %>
                        <tr class="default">
                        <td><strong>Footer Text </strong></td>
                        <td><%= link_to 'Edit FooterText', edit_footertext_path(footertext), method: :get, class: "btn btn-info btn-xs" %></td> 
                        <td><%= link_to 'Destroy FooterText', footertext, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>    
                        <% end %>
                        <% else %>
                        <td><strong>Footer Text </strong></td>
                        <td><%= link_to 'New FooterText', new_footertext_path, method: :get, class: "btn btn-info btn-xs" %></td>
                        <td> --- </td>                            
                        </tr>     
                        <% end %>                      
                    </tbody>
                </table>
            </small>
        </div>
      </div>   
</div>      
</div>    
    
    

app/views/layouts/_footer.html.erb
<br><br>
<div class="push"></div>
<!--==========================Docimer Sticky Footer============================--> 
<% if !cmsadmin_signed_in? %>
  <footer class="navbar footer">
    
 <br>

      <div class="container text-center">
        <div class="row">
          <div class="col-md-12">
            <div class="copyright">
                <small>
                    <% if @footertexts.present? %>
                        <% @footertexts.each do |footertext| %>
                            <%= footertext.text %>
                        <% end %>
                     <% else %>
                         &copy; <small>Copyright. The Docimer Project. All Rights Reserved | 2018 </small>       
                     <% end %>
                </small>
                 
            </div>
          </div>
        </div>
      </div>
  </footer>
<% end %>
<!-- #footer -->
<script>
	$(window).load(function(){
		$('.footer').stickyFooter();
	});
</script>

app/views/layouts/_templating.html.erb
<% @templates.each do |template| %>
    <% if template.bar == 1 %><%= render "layouts/hd/header" %> <% elsif template.bar == 2  %> <%= render "layouts/hd/header2" %>
    <% elsif template.bar == 3  %> <%= render "layouts/hd/header3" %> <% elsif template.bar == 4  %> <%= render "layouts/hd/header4" %>
    <% elsif template.bar == 5  %> <%= render "layouts/hd/header5" %> <% elsif template.bar == 6  %> <%= render "layouts/hd/header6" %>
    <% else %> <%= render "layouts/hd/header" %>
    <% end %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= render "layouts/statement/title" %></title>  
    <meta name="description" content="<% @homes.each do |home| %> <%= home.sub_title %> <% end %>">  
    <link rel="shortcut icon" href="/assets/medium/docimer.ico"/>  
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>      
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<% if cmsadmin_signed_in? %>    
    <body>
        <%= render "layouts/statement/admin_signed" %>
    </body>
    
<% else %>
    <%= render "layouts/statement/admin_not_signed" %> 
<% end %> 
     
</html>

app/views/layouts/hd/_header.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <% if @logotexts.present? %>
            <% @logotexts.each do |logotext| %>
                <%= link_to logotext.text, "/", method: :get, class: "navbar-brand" %>
            <% end %>
        <% else %>  
          <%= link_to "The Docimer Project", "/", method: :get, class: "navbar-brand" %>
        <% end %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% @pages.each do |page| %>
            <li><%= link_to page.title, page, method: :get %></li>
        <% end %>
    <% @sections.each do |section| %>
          <% if section.option.empty? %>
          <% else %>
          <li><%= link_to "Blogs", blogs_path, method: :get %></li>
    <% end %><% end %>
          
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/hd/_header2.html.erb
<!-- Static navbar -->
<ul class="docile-bar">
    <li>
        <% if @logotexts.present? %>
            <% @logotexts.each do |logotext| %>
                <strong><em><%= link_to logotext.text, "/", method: :get %></em></strong>
            <% end %>
        <% else %>  
          <strong><em><%= link_to "The Docimer Project", "/", method: :get %></em></strong>
        <% end %>  
    </li>
    <div style="float:right">
        <% @pages.each do |page| %>
            <li><%= link_to page.title, page, method: :get %></li>
        <% end %>
    <% @sections.each do |section| %>
          <% if section.option.empty? %>
          <% else %>
          <li><%= link_to "Blogs", blogs_path, method: :get %></li>
    <% end %><% end %>
    </div>    
    </ul>

app/views/layouts/hd/_header3.html.erb
<!-- Static navbar -->
<ul class="docile-bar navbar" style="background-color: #A9A9A9;">
    <li>    
        <% if @logotexts.present? %>
            <% @logotexts.each do |logotext| %>
                <strong><em><%= link_to logotext.text, "/", method: :get, class: "header3" %></em></strong>
            <% end %>
        <% else %>  
          <strong><em><%= link_to "The Docimer Project", "/", method: :get, class: "header3" %></em></strong>
        <% end %>           
    </li>
    <div style="float:right">
        <% @pages.each do |page| %>
            <li><%= link_to page.title, page, class: "header3", method: :get %></li>
        <% end %>
    <% @sections.each do |section| %>
          <% if section.option.empty? %>
          <% else %>
          <li><%= link_to "Blogs", blogs_path, class: "header3", method: :get %></li>
    <% end %><% end %>
    </div>    
    </ul>

app/views/layouts/hd/_header4.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default"><div style="background-color: #008B8B; color: white;">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <% if @logotexts.present? %>
            <% @logotexts.each do |logotext| %>
                <%= link_to logotext.text, "/", method: :get, class: "navbar-brand", style: "color: white;" %>
            <% end %>
        <% else %>  
          <%= link_to "The Docimer Project", "/", method: :get, class: "navbar-brand", style: "color: white;" %>
        <% end %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% @pages.each do |page| %>
            <li><%= link_to page.title, page, style: "color: white;", method: :get %></li>
        <% end %>
    <% @sections.each do |section| %>
          <% if section.option.empty? %>
          <% else %>
          <li><%= link_to "Blogs", blogs_path, style: "color: white;", method: :get %></li>
    <% end %><% end %>
          
      </ul>
    </div><!--/.nav-collapse -->
  </div>
    </div>
</nav>

app/views/layouts/hd/_header5.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top"><div style="background-color: #F5F5DC;">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <% if @logotexts.present? %>
            <% @logotexts.each do |logotext| %>
                <%= link_to logotext.text, "/", method: :get, class: "navbar-brand" %>
            <% end %>
        <% else %>  
          <%= link_to "The Docimer Project", "/", method: :get, class: "navbar-brand" %>
        <% end %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% @pages.each do |page| %>
            <li><%= link_to page.title, page, method: :get %></li>
        <% end %>
    <% @sections.each do |section| %>
          <% if section.option.empty? %>
          <% else %>
          <li><%= link_to "Blogs", blogs_path, method: :get %></li>
    <% end %><% end %>
          
      </ul>
    </div><!--/.nav-collapse -->
  </div>
  </div>
</nav>

app/views/layouts/hd/_header6.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <% if @logotexts.present? %>
            <% @logotexts.each do |logotext| %>
                <%= link_to logotext.text, "/", method: :get, class: "navbar-brand" %>
            <% end %>
        <% else %>  
          <%= link_to "The Docimer Project", "/", method: :get, class: "navbar-brand" %>
        <% end %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
            <% @pages.each do |page| %>
                    <li><%= link_to page.title, page, method: :get %></li>
                <% end %>
            <% @sections.each do |section| %>
                  <% if section.option.empty? %>
                  <% else %>
                  <li><%= link_to "Blogs", blogs_path, method: :get %></li>
            <% end %><% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li>
              <a>
                      <% if @navtexts.present? %>
                          <% @navtexts.each do |navtext| %>
                              <%= navtext.text %>
                          <% end %>
                      <% else %>
                          Nav Text: e.g. Phone n0          
                      <% end %> 
              </a>
          
          </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/statement/_admin_not_signed.html.erb
    <% if @designs.present? %>
            <% @designs.each do |design| %>
                <body  style="color: <%= design.text_color.color %>; background-color: <%= design.body_color.color %>;">
            <% end %>    
        <% else %> 
            <body  style="color: #000; background-color: #fff;">    
    <% end %> 
        <% if @templates.present? %>        
            <%= render "layouts/templating" %>
        <% else %> 
            <%= render "layouts/hd/header" %>                
        <% end %>  
        <!-- FLASH --> 
         <% flash.each do |name, msg| %> 
            <div class="alert alert-warning alert-dismissable" style="position:absolute; z-index:999; width: 100%;"> 
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a> 
              <h4><%= content_tag(:div, msg, class: "text-center") %></h4> 
            </div> 
         <% end %>        
    <%= yield %> 
<%= render "layouts/footer" %>    
</body>

app/views/layouts/statement/_admin_signed.html.erb
<% if @designs.present? %>
        <% @designs.each do |design| %>
            <div class="col-md-9"  style="color: <%= design.text_color.color %>; background-color: <%= design.body_color.color %>;">
        <% end %>    
    <% else %> 
        <div class="col-md-9"  style="color: #000; background-color: #fff;">    
<% end %>     
    <% if @templates.present? %>        
        <%= render "layouts/templating" %>
    <% else %> 
        <%= render "layouts/hd/header" %>                
    <% end %> 
    <!-- FLASH --> 
    <% if flash %> <% flash.each do |name, msg| %> 
        <div class="alert alert-danger alert-dismissable" style="position:absolute; z-index:999; width: 95%;"> 
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a> 
          <h4><%= content_tag(:div, msg, class: "text-center") %></h4> 
        </div> 
      <% end %> 
    <% end %>       
    <%= yield %>
        <%= render "layouts/footer" %> 
</div>     
<div class="col-md-3">      
      <%= render "layouts/docimer_sidebar" %>
</div> 

app/views/layouts/statement/_title.html.erb
<% if @logotexts.present? %>
    <% @logotexts.each do |logotext| %>
        <%= logotext.text %>
    <% end %>
<% else %>
     Docimer          
<% end %> 

app/views/templates/_form.html.erb
<%= form_with(model: template, local: true) do |form| %>
  <% if template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bar %>
    <%= form.number_field :bar, id: :template_bar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Templates</h1>

<table>
  <thead>
    <tr>
      <th>Bar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= template.bar %></td>
        <td><%= link_to 'Show', template %></td>
        <td><%= link_to 'Edit', edit_template_path(template) %></td>
        <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Template', new_template_path %>

app/views/templates/new.html.erb
<h1>New Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bar:</strong>
  <%= @template.bar %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>